#
# Copyright (c) 2019, Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Clock
set_property PACKAGE_PIN D13 [get_ports clk]
    set_property IOSTANDARD LVCMOS33 [get_ports clk]
    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# I2C pullup controllers
set_property PACKAGE_PIN P6 [get_ports {I2C_SDA[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_SDA[0]}]
set_property PACKAGE_PIN D10 [get_ports {I2C_SCL[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_SCL[0]}]
set_property PACKAGE_PIN E6 [get_ports {I2C_SDA[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_SDA[1]}]
set_property PACKAGE_PIN K5 [get_ports {I2C_SCL[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_SCL[1]}]
set_property PACKAGE_PIN E2 [get_ports {I2C_SDA[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_SDA[2]}]
set_property PACKAGE_PIN D1 [get_ports {I2C_SCL[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_SCL[2]}]
# Schematic name ADIG_SPARE5
set_property PACKAGE_PIN C16 [get_ports {I2C_RESET}]
    set_property IOSTANDARD LVCMOS33 [get_ports {I2C_RESET}]

# Analog mux
set_property PACKAGE_PIN A9 [get_ports {AN_MUX_PWMOUT}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_PWMOUT}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_PWMOUT}]
# Schematic name MUX_ENABLE
set_property PACKAGE_PIN B6 [get_ports {AN_MUX_ENABLE}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ENABLE}]
    set_property PULLTYPE PULLUP [get_ports {AN_MUX_ENABLE}]
# Schematic name DUT_ANALOG
set_property PACKAGE_PIN B7 [get_ports {AN_MUX_ANALOGINP}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ANALOGINP}]
# Schematic name GND
set_property PACKAGE_PIN A7 [get_ports {AN_MUX_ANALOGINN}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ANALOGINN}]
# Schematic name AN_ADDR0
set_property PACKAGE_PIN C7 [get_ports {AN_MUX_ADDR[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[0]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[0]}]
# Schematic name AN_ADDR1
set_property PACKAGE_PIN C6 [get_ports {AN_MUX_ADDR[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[1]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[1]}]
# Schematic name AN_ADDR2
set_property PACKAGE_PIN C3 [get_ports {AN_MUX_ADDR[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[2]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[2]}]
# Schematic name AN_ADDR3
set_property PACKAGE_PIN C2 [get_ports {AN_MUX_ADDR[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[3]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[3]}]
# Schematic name AN_ADDR4
set_property PACKAGE_PIN B2 [get_ports {AN_MUX_ADDR[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[4]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[4]}]
# Schematic name AN_ADDR5
set_property PACKAGE_PIN A2 [get_ports {AN_MUX_ADDR[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[5]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[5]}]
# Schematic name AN_ADDR6
set_property PACKAGE_PIN C1 [get_ports {AN_MUX_ADDR[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[6]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[6]}]
# Schematic name AN_ADDR7
set_property PACKAGE_PIN B1 [get_ports {AN_MUX_ADDR[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {AN_MUX_ADDR[7]}]
    set_property PULLTYPE PULLDOWN [get_ports {AN_MUX_ADDR[7]}]

# Power measurement
# Schematic name ANIN0
set_property PACKAGE_PIN C8 [get_ports {ANINP[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINP[0]}]
# Schematic name ANIN1
set_property PACKAGE_PIN C9 [get_ports {ANINN[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINN[0]}]
# Schematic name ANIN4
set_property PACKAGE_PIN B9 [get_ports {ANINP[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINP[1]}]
# Schematic name ANIN5
set_property PACKAGE_PIN A10 [get_ports {ANINN[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINN[1]}]
# Schematic name ANIN6
set_property PACKAGE_PIN B12 [get_ports {ANINP[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINP[2]}]
# Schematic name ANIN7
set_property PACKAGE_PIN A12 [get_ports {ANINN[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINN[2]}]
# Schematic name ANIN8
set_property PACKAGE_PIN A13 [get_ports {ANINP[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINP[3]}]
# Schematic name ANIN9
set_property PACKAGE_PIN A14 [get_ports {ANINN[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {ANINN[3]}]

# LEDs
# Schematic name ADIG_SPARE2
set_property PACKAGE_PIN B14 [get_ports {LED[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
    set_property PULLTYPE PULLDOWN [get_ports {LED[0]}]
# Schematic name ADIG_SPARE3
set_property PACKAGE_PIN B15 [get_ports {LED[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
    set_property PULLTYPE PULLDOWN [get_ports {LED[1]}]
# Schematic name ADIG_SPARE4
set_property PACKAGE_PIN A15 [get_ports {LED[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
    set_property PULLTYPE PULLDOWN [get_ports {LED[2]}]

# Buttons
# Schematic name ADIG_SPARE6
set_property PACKAGE_PIN B16 [get_ports {RESET_BTN}]
    set_property IOSTANDARD LVCMOS33 [get_ports {RESET_BTN}]
    set_property PULLTYPE PULLUP [get_ports {RESET_BTN}]

# ID Pins
set_property PACKAGE_PIN B5 [get_ports {DIG_ID[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DIG_ID[0]}]
set_property PACKAGE_PIN A5 [get_ports {DIG_ID[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DIG_ID[1]}]
set_property PACKAGE_PIN A4 [get_ports {DIG_ID[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {DIG_ID[2]}]

# Self reprogram pin
# Schematic name SPARE0
set_property PACKAGE_PIN K12 [get_ports {REPROGRAM}]
    set_property IOSTANDARD LVCMOS33 [get_ports {REPROGRAM}]
    set_property PULLTYPE PULLUP [get_ports {REPROGRAM}]

# Quad SPI Flash
set_property PACKAGE_PIN J13 [get_ports {SPI_IO[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SPI_IO[0]}]
    set_property PULLTYPE PULLUP [get_ports {SPI_IO[0]}]
set_property PACKAGE_PIN J14 [get_ports {SPI_IO[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SPI_IO[1]}]
    set_property PULLTYPE PULLUP [get_ports {SPI_IO[1]}]
set_property PACKAGE_PIN K15 [get_ports {SPI_IO[2]}]
   set_property IOSTANDARD LVCMOS33 [get_ports {SPI_IO[2]}]
   set_property PULLTYPE PULLUP [get_ports {SPI_IO[2]}]
set_property PACKAGE_PIN K16 [get_ports {SPI_IO[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SPI_IO[3]}]
    set_property PULLTYPE PULLUP [get_ports {SPI_IO[3]}]
set_property PACKAGE_PIN L12 [get_ports SPI_CS]
    set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
    set_property PULLTYPE PULLUP [get_ports {SPI_CS}]
##SPI clock (CCLK_0) is accessed through the STARTUPE2 primitive.

# IO Port
set_property PACKAGE_PIN C12 [get_ports {IO[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[0]}]
set_property PACKAGE_PIN D11 [get_ports {IO[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[1]}]
set_property PACKAGE_PIN C11 [get_ports {IO[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[2]}]
set_property PACKAGE_PIN E11 [get_ports {IO[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[3]}]
set_property PACKAGE_PIN B11 [get_ports {IO[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[4]}]
set_property PACKAGE_PIN D9 [get_ports {IO[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[5]}]
set_property PACKAGE_PIN B10 [get_ports {IO[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[6]}]
set_property PACKAGE_PIN D8 [get_ports {IO[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[7]}]
set_property PACKAGE_PIN A8 [get_ports {IO[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[8]}]
set_property PACKAGE_PIN D15 [get_ports {IO[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[9]}]
set_property PACKAGE_PIN D16 [get_ports {IO[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[10]}]
set_property PACKAGE_PIN E15 [get_ports {IO[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[11]}]
set_property PACKAGE_PIN E16 [get_ports {IO[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[12]}]
set_property PACKAGE_PIN F14 [get_ports {IO[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[13]}]
set_property PACKAGE_PIN F15 [get_ports {IO[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[14]}]
set_property PACKAGE_PIN G15 [get_ports {IO[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[15]}]
set_property PACKAGE_PIN G11 [get_ports {IO[16]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[16]}]
set_property PACKAGE_PIN G12 [get_ports {IO[17]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[17]}]
set_property PACKAGE_PIN F13 [get_ports {IO[18]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[18]}]
set_property PACKAGE_PIN F12 [get_ports {IO[19]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[19]}]
set_property PACKAGE_PIN E13 [get_ports {IO[20]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[20]}]
set_property PACKAGE_PIN D14 [get_ports {IO[21]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[21]}]
set_property PACKAGE_PIN C13 [get_ports {IO[22]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[22]}]
set_property PACKAGE_PIN E12 [get_ports {IO[23]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[23]}]
set_property PACKAGE_PIN L13 [get_ports {IO[24]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[24]}]
set_property PACKAGE_PIN L14 [get_ports {IO[25]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[25]}]
set_property PACKAGE_PIN K13 [get_ports {IO[26]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[26]}]
set_property PACKAGE_PIN H13 [get_ports {IO[27]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[27]}]
set_property PACKAGE_PIN H12 [get_ports {IO[28]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[28]}]
set_property PACKAGE_PIN H11 [get_ports {IO[29]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[29]}]
set_property PACKAGE_PIN G14 [get_ports {IO[30]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[30]}]
set_property PACKAGE_PIN G16 [get_ports {IO[31]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[31]}]
set_property PACKAGE_PIN H16 [get_ports {IO[32]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[32]}]
set_property PACKAGE_PIN H14 [get_ports {IO[33]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[33]}]
set_property PACKAGE_PIN J16 [get_ports {IO[34]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[34]}]
set_property PACKAGE_PIN J15 [get_ports {IO[35]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[35]}]
# Schematic name ADIG_SPARE1
set_property PACKAGE_PIN C14 [get_ports {IO[36]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[36]}]
set_property PACKAGE_PIN M14 [get_ports {IO[37]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[37]}]
set_property PACKAGE_PIN M16 [get_ports {IO[38]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[38]}]
set_property PACKAGE_PIN M15 [get_ports {IO[39]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[39]}]
set_property PACKAGE_PIN R16 [get_ports {IO[40]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[40]}]
set_property PACKAGE_PIN R15 [get_ports {IO[41]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[41]}]
set_property PACKAGE_PIN P16 [get_ports {IO[42]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[42]}]
set_property PACKAGE_PIN P15 [get_ports {IO[43]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[43]}]
set_property PACKAGE_PIN N16 [get_ports {IO[44]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[44]}]
set_property PACKAGE_PIN P14 [get_ports {IO[45]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[45]}]
set_property PACKAGE_PIN N14 [get_ports {IO[46]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[46]}]
set_property PACKAGE_PIN N13 [get_ports {IO[47]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[47]}]
set_property PACKAGE_PIN P11 [get_ports {IO[48]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[48]}]
set_property PACKAGE_PIN R13 [get_ports {IO[49]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[49]}]
set_property PACKAGE_PIN T13 [get_ports {IO[50]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[50]}]
set_property PACKAGE_PIN M12 [get_ports {IO[51]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[51]}]
set_property PACKAGE_PIN N12 [get_ports {IO[52]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[52]}]
set_property PACKAGE_PIN P13 [get_ports {IO[53]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[53]}]
set_property PACKAGE_PIN T14 [get_ports {IO[54]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[54]}]
set_property PACKAGE_PIN T15 [get_ports {IO[55]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[55]}]
set_property PACKAGE_PIN R12 [get_ports {IO[56]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[56]}]
set_property PACKAGE_PIN T12 [get_ports {IO[57]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[57]}]
set_property PACKAGE_PIN R11 [get_ports {IO[58]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[58]}]
set_property PACKAGE_PIN N11 [get_ports {IO[59]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[59]}]
set_property PACKAGE_PIN R10 [get_ports {IO[60]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[60]}]
set_property PACKAGE_PIN T10 [get_ports {IO[61]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[61]}]
set_property PACKAGE_PIN T9 [get_ports {IO[62]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[62]}]
set_property PACKAGE_PIN R8 [get_ports {IO[63]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[63]}]
set_property PACKAGE_PIN T8 [get_ports {IO[64]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[64]}]
set_property PACKAGE_PIN T7 [get_ports {IO[65]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[65]}]
set_property PACKAGE_PIN R7 [get_ports {IO[66]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[66]}]
set_property PACKAGE_PIN M6 [get_ports {IO[67]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[67]}]
set_property PACKAGE_PIN P8 [get_ports {IO[68]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[68]}]
set_property PACKAGE_PIN P9 [get_ports {IO[69]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[69]}]
set_property PACKAGE_PIN N9 [get_ports {IO[70]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[70]}]
set_property PACKAGE_PIN P10 [get_ports {IO[71]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[71]}]
set_property PACKAGE_PIN P4 [get_ports {IO[72]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[72]}]
set_property PACKAGE_PIN L5 [get_ports {IO[73]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[73]}]
set_property PACKAGE_PIN T5 [get_ports {IO[74]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[74]}]
set_property PACKAGE_PIN R5 [get_ports {IO[75]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[75]}]
set_property PACKAGE_PIN P5 [get_ports {IO[76]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[76]}]
set_property PACKAGE_PIN M5 [get_ports {IO[77]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[77]}]
set_property PACKAGE_PIN N6 [get_ports {IO[78]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[78]}]
set_property PACKAGE_PIN R6 [get_ports {IO[79]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[79]}]
set_property PACKAGE_PIN T4 [get_ports {IO[80]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[80]}]
set_property PACKAGE_PIN N4 [get_ports {IO[81]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[81]}]
set_property PACKAGE_PIN T3 [get_ports {IO[82]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[82]}]
set_property PACKAGE_PIN R3 [get_ports {IO[83]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[83]}]
set_property PACKAGE_PIN T2 [get_ports {IO[84]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[84]}]
set_property PACKAGE_PIN R2 [get_ports {IO[85]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[85]}]
set_property PACKAGE_PIN R1 [get_ports {IO[86]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[86]}]
set_property PACKAGE_PIN P1 [get_ports {IO[87]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[87]}]
set_property PACKAGE_PIN J5 [get_ports {IO[88]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[88]}]
set_property PACKAGE_PIN J3 [get_ports {IO[89]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[89]}]
set_property PACKAGE_PIN K3 [get_ports {IO[90]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[90]}]
set_property PACKAGE_PIN L3 [get_ports {IO[91]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[91]}]
set_property PACKAGE_PIN L4 [get_ports {IO[92]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[92]}]
set_property PACKAGE_PIN M4 [get_ports {IO[93]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[93]}]
set_property PACKAGE_PIN N3 [get_ports {IO[94]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[94]}]
set_property PACKAGE_PIN P3 [get_ports {IO[95]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[95]}]
set_property PACKAGE_PIN G4 [get_ports {IO[96]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[96]}]
set_property PACKAGE_PIN G5 [get_ports {IO[97]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[97]}]
set_property PACKAGE_PIN H3 [get_ports {IO[98]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[98]}]
set_property PACKAGE_PIN H4 [get_ports {IO[99]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[99]}]
set_property PACKAGE_PIN H2 [get_ports {IO[100]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[100]}]
set_property PACKAGE_PIN H1 [get_ports {IO[101]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[101]}]
set_property PACKAGE_PIN H5 [get_ports {IO[102]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[102]}]
set_property PACKAGE_PIN J4 [get_ports {IO[103]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[103]}]
set_property PACKAGE_PIN N2 [get_ports {IO[104]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[104]}]
set_property PACKAGE_PIN N1 [get_ports {IO[105]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[105]}]
set_property PACKAGE_PIN M2 [get_ports {IO[106]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[106]}]
set_property PACKAGE_PIN M1 [get_ports {IO[107]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[107]}]
set_property PACKAGE_PIN L2 [get_ports {IO[108]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[108]}]
set_property PACKAGE_PIN K2 [get_ports {IO[109]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[109]}]
set_property PACKAGE_PIN K1 [get_ports {IO[110]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[110]}]
set_property PACKAGE_PIN J1 [get_ports {IO[111]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[111]}]
set_property PACKAGE_PIN E3 [get_ports {IO[112]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[112]}]
set_property PACKAGE_PIN E1 [get_ports {IO[113]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[113]}]
set_property PACKAGE_PIN F5 [get_ports {IO[114]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[114]}]
set_property PACKAGE_PIN F4 [get_ports {IO[115]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[115]}]
set_property PACKAGE_PIN F3 [get_ports {IO[116]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[116]}]
set_property PACKAGE_PIN F2 [get_ports {IO[117]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[117]}]
set_property PACKAGE_PIN G2 [get_ports {IO[118]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[118]}]
set_property PACKAGE_PIN G1 [get_ports {IO[119]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[119]}]
set_property PACKAGE_PIN A3 [get_ports {IO[120]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[120]}]
set_property PACKAGE_PIN B4 [get_ports {IO[121]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[121]}]
set_property PACKAGE_PIN D6 [get_ports {IO[122]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[122]}]
set_property PACKAGE_PIN D5 [get_ports {IO[123]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[123]}]
set_property PACKAGE_PIN C4 [get_ports {IO[124]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[124]}]
set_property PACKAGE_PIN D4 [get_ports {IO[125]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[125]}]
set_property PACKAGE_PIN D3 [get_ports {IO[126]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[126]}]
set_property PACKAGE_PIN E5 [get_ports {IO[127]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {IO[127]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
